spring:
  datasource:
    url: jdbc:sqlite:${user.home}/AppData/Roaming/InteriorERP/interior.db
    driver-class-name: org.sqlite.JDBC
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

app:
  storage:
    type: local
